echo ""
echo "#########################################################################"
echo "Setup completed!"
echo "Login to the site and access the Carbon Fields Options page at:"
echo "http://localhost:8099/wp-admin/admin.php?page=crb_carbon_fields_container_my_theme_options.php"
echo ""
echo "Username: admin"
echo "Password: password"
echo ""
echo "Access Carbon Fields theme options from the sidebar..."
echo "#########################################################################"
echo ""
